name: Deploy Code
on: 
    workflow_dispatch:
    release:
        types: [published]

concurrency:
    group: deploy-${{ github.ref }}
    cancel-in-progress: true

env:
    AZURE_WEBAPP_PACKAGE: 'test-artifact'

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: npm install, build
              run: |
                npm install
                npm run build
            - name: Create Zip Artifact
              run: |
               zip -r ${AZURE_WEBAPP_PACKAGE}.zip dist/ package.json src/versions/
            - name: Create artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.AZURE_WEBAPP_PACKAGE}}
                path: ${{ env.AZURE_WEBAPP_PACKAGE}}.zip
    
    deploy-dev:
        permissions:
            contents: none
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "DevTest"

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: ${{ env.AZURE_WEBAPP_PACKAGE }}
                path: ./
            - run: echo "Deployed to devtest"
    
    deploy-uat:
        permissions:
            contents: none
        runs-on: ubuntu-latest
        needs: [build, deploy-dev]
        environment:
            name: "UAT"

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
               name: ${{ env.AZURE_WEBAPP_PACKAGE }}
               path: ./
            - run: echo "Deployed to UAT"
    
    deploy-staging:
        runs-on: ubuntu-latest
        needs: [build, deploy-dev, deploy-uat]
        steps:
            - run: echo "Staging"
