name: semantic versioning

on:
    push:
        branches:
            - main
        tags-ignore:
            - "**"

jobs:
    versioning:
        name: Versioning
        runs-on: ubuntu-latest

        permissions:
            contents: write
            discussions: write
            issues: write
            pull-requests: write

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                persist-credentials: false

            - name: Install dependencies
              run: npm ci

            - name: Run versioning script
              run: npm run version:package
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


